"""empty message

Revision ID: 406649095a8
Revises: None
Create Date: 2014-07-09 18:41:19.288894

"""

# revision identifiers, used by Alembic.
revision = '406649095a8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    	'post',
		sa.Column('id', sa.Integer, primary_key=True),
		sa.Column('title', sa.Unicode(120)),
		sa.Column('text', sa.UnicodeText, nullable=False),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
